# Generated by Django 5.2.3 on 2025-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=256, verbose_name='Модель Машины')),
                ('description', models.CharField(max_length=3000, verbose_name='Краткое Описание')),
                ('parameters', models.CharField(max_length=3000, verbose_name='Параметры')),
            ],
            options={
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
